import "@/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { TRPCReactProvider } from "@/trpc/react";
import { ClerkProvider } from "@clerk/nextjs";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/themes-provider";

export const metadata: Metadata = {
  title: "Theera",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.svg" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
      <ClerkProvider>
        <html lang="en" className={`${GeistSans.variable}`}>
          <body>
            <TRPCReactProvider>{children}</TRPCReactProvider>
            <Toaster richColors />
          </body>
        </html>
      </ClerkProvider>
  );
}
